Практическое задание №5 (часть 1)

In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
from scipy.optimize import fsolve
import itertools
import math
import sys

Задание №1

Вычислить обратную матрицу (5Е)^(-1)

In [9]:
#E = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]])
E = np.identity(5)
print(E)
print("Матрица")
a = 5 * E
print(a)
a_ = np.linalg.inv(a)
print("Обратная матрица")
print(a_)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Матрица
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
Обратная матрица
[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


Задание №2

Вычислите определитель

In [11]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]])
print(a)
det = np.linalg.det(a)
print(det)

[[1 2 3]
 [4 0 6]
 [7 8 9]]
59.999999999999986


Задание №3

Вычислите матрицу, обратную данной

In [12]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]])
print("Матрица")
print(a)
a_ = np.linalg.inv(a)
print("Обратная матрица")
print(a_)

Матрица
[[1 2 3]
 [4 0 6]
 [7 8 9]]
Обратная матрица
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


Задание №4

Вычислите скалярное произведение двух векторов: (1, 5)  и  (2, 8)

In [13]:
a = np.array([1,5], float)
b = np.array([2,8], float)
ab_ = np.inner(a,b)
print(ab_)

42.0


Задание №5

Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

In [15]:
a = np.array([1,5,0], float)
b = np.array([2,8,7], float)
c = np.array([7,1.5,3], float)
axb = np.cross(a,b)
axb_c = np.inner(axb,c)
print(axb_c)
bxc = np.cross(b,c)
a_bxc = np.inner(a,bxc)
print(a_bxc)

228.5
228.5
